apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gcs-flexvolume
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gcs-flexvolume
  template:
    metadata:
      labels:
        app: gcs-flexvolume
    spec:
      initContainers:
        - name: install
          image: outlaw11a/gcs-flexvolume
          command:
            - /init.sh
            - /flexvolume-hostbin/
            - /flexvolume-plugindir/
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /flexvolume-plugindir
              name: flexvolume-plugindir
            - mountPath: /flexvolume-hostbin
              name: flexvolume-hostbin
      containers:
        - name: pause
          image: gcr.io/google_containers/pause
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: /home/kubernetes/flexvolume/
        - name: flexvolume-hostbin
          hostPath:
            path: /home/kubernetes/bin/

